baseConfig: "tsconfig.base.json"
mode: loose
defaultFileMode: default
generatePaths: true
files: 
  build: 
    presets: 
      - build
presets:
  build:
    exclude:
      - "src/**/*.spec.*"
      - "src/**/__fixtures__/**/*"
      - "src/**/__mocks__/**/*"
  lib:
    include:
      - "src/**/*"
    compilerOptions:
      composite: true
      incremental: true
      rootDir: "./src"
      outDir: "./dist"
      tsBuildInfoFile: "./dist/.tsbuildinfo"

  commonjs:
    compilerOptions:
      module: "Node16"
      moduleResolution: "Node16"
  docusaurus:
    extends: "@docusaurus/tsconfig"
    compilerOptions:
      noEmit: true
      baseUrl: "."
      rootDir: "src"
      tsBuildInfoFile: "./node_modules/.tmp/tsconfig.app.tsbuildInfo"
    include:
      - "src/**/*"
  docusaurusBuild:
    exclude: 
      - "src/**/*"
  nextApp:
    extends: "./tsconfig.next.json"
    compilerOptions:
      lib:
        - dom
        - dom.iterable
        - esnext
      allowJs: true
      skipLibCheck: true
      strict: true
      noEmit: true
      esModuleInterop: true
      module: esnext
      moduleResolution: Node
      resolveJsonModule: true
      isolatedModules: true
      jsx: preserve
      incremental: true
      plugins:
        - name: next
      paths:
        "@/*":
          - "./*"
    include:
      - next-env.d.ts
      - "**/*.ts"
      - "**/*.tsx"
      - ".next/types/**/*.ts"
    exclude:
      - node_modules
  react:
    compilerOptions:
      jsx: react-jsx
  viteApp:
    compilerOptions:
      composite: true
      tsBuildInfoFile: "./node_modules/.tmp/tsconfig.app.tsbuildinfo"
      target: ES2020
      useDefineForClassFields: true
      lib:
        - ES2020
        - DOM
        - DOM.Iterable
      skipLibCheck: true
      allowImportingTsExtensions: true
      resolveJsonModule: true
      isolatedModules: true
      moduleDetection: force
      noEmit: true
      jsx: react-jsx
      strict: true
      noUnusedLocals: true
      noUnusedParameters: true
      noFallthroughCasesInSwitch: true
  storybook:
    compilerOptions:
      noEmit: true
      baseUrl: "."
      rootDir: "src"
      tsBuildInfoFile: "./node_modules/.tmp/tsconfig.app.tsbuildInfo"
    include:
      - "src/**/*"