baseConfig: "tsconfig.base.json"
mode: loose
defaultFileMode: default
generatePaths: true
presets:
  lib:
    include:
      - "src/**/*"
    # TODO: Remove these once the tsconfig/tsconfig.build refactor is done
    exclude:
      - "src/**/*.spec.*"
      - "src/**/__fixtures__/**/*"
      - "src/**/__mocks__/**/*"
    compilerOptions:
      composite: true
      incremental: true
      rootDir: "./src"
      outDir: "./dist"
      tsBuildInfoFile: "./dist/.tsbuildinfo"
  commonjs: 
    compilerOptions:
      module: "Node16"
      moduleResolution: "Node16"
  docusaurus:
    extends: "@docusaurus/tsconfig"
    compilerOptions:
      noEmit: true
      baseUrl: "."
      rootDir: "src"
      tsBuildInfoFile: "./node_modules/.tmp/tsconfig.app.tsbuildInfo"
    include:
      - "src/**/*"
    # TODO: Remove these once the tsconfig/tsconfig.build refactor is done
    exclude:
      - "src/**/*.spec.*"
      - "src/**/__fixtures__/**/*"
      - "src/**/__mocks__/**/*"
  react:
    compilerOptions:
      jsx: react-jsx
  viteApp:
    compilerOptions:
      composite: true
      tsBuildInfoFile: "./node_modules/.tmp/tsconfig.app.tsbuildinfo"
      target: ES2020
      useDefineForClassFields: true
      lib:
        - ES2020
        - DOM
        - DOM.Iterable
      skipLibCheck: true
      allowImportingTsExtensions: true
      resolveJsonModule: true
      isolatedModules: true
      moduleDetection: force
      noEmit: true
      jsx: react-jsx
      strict: true
      noUnusedLocals: true
      noUnusedParameters: true
      noFallthroughCasesInSwitch: true
