baseConfig: "tsconfig.base.json"
mode: loose
defaultFileMode: default
generatePaths: true
presets: 
  lib: 
    include: 
      - "src/**/*"
    compilerOptions:
      rootDir: 'src'
  docusaurus:
    extends: "@docusaurus/tsconfig"
    compilerOptions: 
      baseUrl: "."
  