initScope: sabinmarcu

nodeLinker: node-modules

npmAuthToken: "${YARN_NPM_AUTH_TOKEN:-NO_TOKEN}"

npmPublishAccess: public

packageExtensions:
  moize@*:
    dependencies:
      a: "*"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
