compressionLevel: mixed

enableGlobalCache: false

initScope: sabinmarcu

nodeLinker: node-modules

npmAuthToken: "${YARN_NPM_AUTH_TOKEN:-NO_TOKEN}"

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.0.1.cjs

nmMode: 'hardlinks-global'