name: omnirepo
packageManager: yarn@3.3.0
type: module
dependencies:
  "@moonrepo/cli": ^0.20.0
  "@sabinmarcu/eslint-config": workspace:*
  eslint: ^8.30.0
  husky: ^8.0.2
  jest: ^29.3.1
  mkdist: ^1.0.0
  typescript: ^4.9.4
  unbuild: ^1.0.2
  "@commitlint/cli": ^17.3.0
  "@commitlint/config-conventional": ^17.3.0
scripts:
  moon: $(yarn bin moon)
  postinstall: "husky install"
devDependencies:
  "@types/eslint": ^8.4.10
  "@types/jest": ^29.2.4
workspaces:
  - ./packages/*
engines:
  node: 18.12.0
