project:
  name: "@sabinmarcu/eslint-config"
  alias: eslint-config
  description: Personal ESLint configuration
  channel: '#config'
  maintainers:
    - Sabin Marcu
  owner: Sabin Marcu

language: typescript
type: library

workspace:
  inheritedTasks: 
    exclude:
      - stub
  