project:
  name: "@sabinmarcu/eslint-config"
  alias: eslint-config
  description: Moon ESLint configuration
  channel: '#eslint-config'
  maintainers:
    - Sabin Marcu
  owner: Sabin Marcu

language: typescript
type: library

workspace:
  inheritedTasks: 
    exclude:
      - stub
  