setup:
  /:
    packages:
      package-a:
        package.json: |
          {
            name: "package-a",
            version: "1.0.0"
          }
        tsconfig.json: yes
      package-b:
        package.json: |
          {
            name: "package-b",
            version: "1.0.0"
          }
        tsconfig.json: yes
input:
  rootDirectory: '/'
  workspaces: 
    - packages/*
output: 
  - packages/package-a/tsconfig.json
  - packages/package-b/tsconfig.json
