project:
  name: commitlint-config-workspaces
  description: Commitlint workspace config
  channel: '#config'
  maintainers:
    - Sabin Marcu
  owner: Sabin Marcu

language: typescript
type: library

workspace:
  inheritedTasks: 
    exclude:
      - dev
  
dependsOn:
  - utils-repo