# https://moonrepo.dev/docs/config/global-project
$schema: 'https://moonrepo.dev/schemas/global-project.json'

fileGroups:
  configs:
    - '*.{js,json}'

  sources:
    - 'src/**/*'

  buildConfig:
    - '/.config/build.config.ts'

  tests:
    - 'src/**/*.spec.*'

tasks:
  devExports: 
    command: '../../scripts/exports.js'
    args:
      - --dev
    inputs:
      - package.json
    outputs: 
      - package.json
    local: true

  fixExports: 
    command: '../../scripts/exports.js'
    inputs:
      - package.json
    outputs: 
      - package.json
    cache: false
    options:
      runInCI: false

  build: 
    command: 'unbuild'
    deps: 
      - '~:fixExports'
      - '^:build'
    inputs: 
      - '@globs(sources)'
      - '@files(buildConfig)'
    outputs: 
      - esm
      - cjs

  dev:
    command: 'unbuild --stub'
    deps: 
      - '~:devExports'
      - '^:dev'
    inputs: 
      - '@globs(sources)'
      - '@files(buildConfig)'
    local: true

  lint: 
    command: 'eslint'
    deps:
      - eslint-config:build
    inputs: 
      - '@globs(sources)'

  test: 
    command: 'jest'
    args: 
      - --passWithNoTests
    deps:
      - '~:build'
    inputs: 
      - '@globs(sources)'