# https://moonrepo.dev/docs/config/global-project
$schema: 'https://moonrepo.dev/schemas/global-project.json'

fileGroups:
  configs:
    - '*.{js,json}'

  sources:
    - 'src/**/*'

  buildConfig:
    - '/.config/build.config.ts'

  tests:
    - 'src/**/*.spec.*'

tasks:
  init:
    command: 'echo "Initializing project..."'
    type: 'system'
    deps: 
      - eslint-config:build
      - commitlint-config-workspaces:build
    cache: false
    options: 
      runInCI: false
    
  devExports: 
    command: '../../scripts/exports.js'
    args:
      - --dev
    inputs:
      - package.json
    outputs: 
      - package.json
    cache: false
    options:
      runInCI: false

  fixExports: 
    command: '../../scripts/exports.js'
    inputs:
      - package.json
    outputs: 
      - package.json
    cache: false
    options:
      runInCI: false

  build: 
    command: 'unbuild'
    deps: 
      - '^:build'
      - '~:fixExports'
    inputs: 
      - '@globs(sources)'
      - '@files(buildConfig)'
    outputs: 
      - esm
      - cjs

  dev:
    command: 'unbuild --stub'
    deps: 
      - '^:dev'
      - '~:devExports'
    inputs: 
      - '@globs(sources)'
      - '@files(buildConfig)'
    cache: false
    options:
      runInCI: false

  lint: 
    command: 'eslint'
    deps:
      - eslint-config:build
    inputs: 
      - '@globs(sources)'