import type { Metadata } from 'next';
import {
  VT323,
} from 'next/font/google';
import './theme.css.ts';
import './globals.css.ts';
import { getThemeVariant } from '@/components/ThemeSelector.core.ssr';
import { variantSelector } from '@sabinmarcu/website-theme';
import {
  rootBackgroundStyle,
  // scanLinesStyle,
} from './layout.css';

const rootFont = VT323({
  variable: '--font-root',
  subsets: ['latin'],
  preload: true,
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      {...{ [variantSelector]: await getThemeVariant() }}
    >
      <body
       className={[
         rootFont.variable,
         rootFont.className,
         rootBackgroundStyle,
       ].join(' ')}
      >
        {children}
      </body>
    </html>
  );
}

/* <span className={scanLinesStyle}></span> */
