name: 'CI Pipeline'
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: 'yarn install --immutable'

      - name: Run CI Tasks
        run: 'yarn moon ci'

      - name: Run Coverage
        run: 'yarn moon run :coverage'

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with: 
          file: ./coverage/clover.yml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - uses: 'moonrepo/run-report-action@v3'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}