name: 'CI Pipeline'
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch: 
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: 'yarn install --immutable'

      - name: Save Yarn Cache
        uses: actions/upload-artifact@v2
        with:
          name: yarn-cache
          path: .yarn

      - name: Run CI Tasks
        run: 'yarn moon ci'
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
          MOONBASE_ACCESS_KEY: ${{ secrets.MOONBASE_ACCESS_KEY }}

      - name: Report Moon CI Status
        uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Built Files
        uses: actions/upload-artifact@v2
        with:
          name: built-repo
          path: packages

  coverage: 
    name: 'Coverage'
    runs-on: 'ubuntu-latest'
    needs: ci
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v3'

      - name: Setup Environment
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'

      - name: Download Yarn Cache
        uses: actions/download-artifact@v2
        with:
          name: yarn-cache
          path: .yarn

      - name: Download Built Files
        uses: actions/download-artifact@v2
        with:
          name: built-repo
          path: packages

      - name: Install Dependencies
        run: 'yarn install --immutable'

      - name: Run setup
        run: 'yarn moon run root:init'

      - name: Run Coverage
        run: 'yarn coverage'

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with: 
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true