name: 'CI Pipeline'

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: 

jobs:
  ci:
    name: 'Build / Test / Report'
    runs-on: 'ubuntu-latest'
    outputs: 
      has_versioning: ${{ steps.check_versioning.outputs.files_exists }}
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: "Check if versioning is requested"
        uses: andstor/file-existence-action@v2
        id: check_versioning
        with:
          files: ".yarn/versions/*"

      - name: Setup Environment
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: 'yarn install --immutable'

      - name: Run CI Tasks
        run: 'yarn moon ci'
        env:
          MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
          MOONBASE_ACCESS_KEY: ${{ secrets.MOONBASE_ACCESS_KEY }}

      - name: Report Moon CI Status
        uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

  versioning: 
    name: "Versioning"
    runs-on: 'ubuntu-latest'
    needs: ci
    if: needs.ci.outputs.has_versioning == 'true' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: 'yarn install --immutable'

      - name: Run versioning
        run: 'yarn version apply --all'

      - name: Publish packages
        run: 'yarn moon run :publish'
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}          
      
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Save Versioning
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: "chore(ci): Automatic Versioning"
          commit_options: '--no-verify --signoff --gpg-sign'
          push_options: '--force'
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
          commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"

  coverage: 
    name: 'Coverage'
    runs-on: 'ubuntu-latest'
    needs: ci
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: 'yarn install --immutable'

      - name: Run setup
        run: 'yarn moon run :build'

      - name: Run Coverage
        run: 'yarn coverage'

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with: 
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true